project:
  type: website

website:
  site-url: https://example.com
  title: "Home"
  description: "une page perso"
  navbar:
    right:
      - text: BLOG
        href: blog.qmd
      - text: ABOUT
        href: about.qmd
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: "https://be.linkedin.com/in/nabil-sheikh-hassan-a9701943"
        aria-label: "LinkedIn"
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: "https://bsky.app/profile/nabsheikhhassan.bsky.social"
        aria-label: "Bluesky"
      - text: "{{< iconify fa6-brands:google-scholar >}}"
        href: "https://scholar.google.be/citations?user=JQd40mQAAAAJ&hl=en"
        aria-label: "Google Scholar"
  page-footer:
    border: true
    left: "2025"
    center: 
      - text: "Licence CC BY-NC-ND 4.0."
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
babelquarto:
  languagecodes:
  - name: en
    text: "EN"
  - name: fr
    text: "FR"
  mainlanguage: 'fr'
  languages: ['en']
title-en: Home
description-en: personal webpage
author-en: Nabil Sheikh Hassan
lang: fr
